---
- name: setup node
  hosts: ubuntu
  vars_files:
    - vars.yml
  gather_facts: false
  become: true

  tasks:
    - name: Update the Ubuntu package cache
      apt: update_cache=yes cache_valid_time=604800

    - name: Install system packages
      apt: package={{system_packages}} state=present

    - name: Install python packages
      pip: name={{python_packages}} executable=pip3

    - name: Create user groups
      group: name={{item.name}} state={{item.state | default('present')}}
      with_items: "{{ users }}"

    - name: Create users
      user: name={{ item.name }} state={{item.state | default('present')}} group={{ item.name }} groups={{item.groups}} shell=/bin/bash
      with_items: "{{ users }}"

    - name: Adds SSH keys
      authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
      with_subelements:
         - "{{ users }}"
         - authorized_keys

    - name: Add user files
      copy: src={{ item.1 }} dest=/home/{{ item.0.name }}/.ssh/
      with_subelements:
          - "{{ users }}"
          - files

    - name: Disable root login
      lineinfile: "dest=/etc/ssh/sshd_config state=present regexp='^PermitRootLogin' line='PermitRootLogin no'"

    - name: Disable password authentication
      lineinfile: "dest=/etc/ssh/sshd_config state=present regexp='^PasswordAuthentication' line='PasswordAuthentication yes'"

    - name: Enable password less sudo for users in sudo group
      lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL:ALL) NOPASSWD:ALL'"
